import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Icon from 'react-native-vector-icons/Feather';
import { COLORS } from '../../../constants/colors';
import { SPACING } from '../../../constants/spacing';
import { StatusBarManager } from '../../../shared/components';

const SECTIONS = [
  {
    title: '1. Information We Collect',
    body: 'We collect information you provide directly (name, email, phone, address) and information generated by your use of the app (orders, browsing activity, device data).',
  },
  {
    title: '2. How We Use Your Information',
    body: 'Your data is used to process orders, personalise your shopping experience, improve our services, and communicate important updates.',
  },
  {
    title: '3. Data Sharing',
    body: 'We share data with delivery partners, payment processors, and sellers only as required to fulfil your orders. We do not sell your personal data to third parties.',
  },
  {
    title: '4. Data Security',
    body: 'We use industry-standard encryption and security practices to protect your data from unauthorized access, alteration or disclosure.',
  },
  {
    title: '5. Your Rights',
    body: 'You can access, update, download or delete your personal data at any time from the Privacy Center in your account settings.',
  },
  {
    title: '6. Cookies & Tracking',
    body: 'We use cookies and similar technologies to remember your preferences and understand how you use the app.',
  },
  {
    title: '7. Contact Us',
    body: 'If you have questions about this policy, please reach out to our support team through the Help Center.',
  },
];

const PrivacyPolicyScreen = ({ navigation }) => {
  const insets = useSafeAreaInsets();

  return (
    <View style={styles.container}>
      <StatusBarManager barStyle="dark-content" themeColor={COLORS.surface} />

      <View style={[styles.header, { paddingTop: Math.max(insets.top, 12) }]}>
        <TouchableOpacity onPress={() => navigation && navigation.goBack()} style={styles.backBtn}>
          <Icon name="arrow-left" size={20} color={COLORS.textPrimary} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Privacy Policy</Text>
      </View>

      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scrollContent}>
        <Text style={styles.updatedText}>Last updated: 1 January 2026</Text>

        {SECTIONS.map((section) => (
          <View key={section.title} style={styles.section}>
            <Text style={styles.sectionTitle}>{section.title}</Text>
            <Text style={styles.sectionBody}>{section.body}</Text>
          </View>
        ))}
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    paddingHorizontal: SPACING.l,
    paddingBottom: SPACING.m,
  },
  backBtn: {
    marginRight: SPACING.m,
  },
  headerTitle: {
    fontSize: 19,
    fontWeight: '500',
    color: COLORS.textPrimary,
  },
  scrollContent: {
    paddingHorizontal: SPACING.l,
    paddingTop: SPACING.l,
    paddingBottom: SPACING.xxxl,
  },
  updatedText: {
    fontSize: 12,
    color: COLORS.textTertiary,
    marginBottom: SPACING.l,
  },
  section: {
    marginBottom: SPACING.xl,
  },
  sectionTitle: {
    fontSize: 14.5,
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: SPACING.xs,
  },
  sectionBody: {
    fontSize: 13,
    color: COLORS.textSecondary,
    lineHeight: 19,
  },
});

export default PrivacyPolicyScreen;
